# no official version number!
{% set version = "3.0.7.post0" %}

package:
  name: sibelia
  version: {{ version }}

source:
  fn: Sibelia-{{ version }}.tar.gz
  url: https://github.com/bioinf/Sibelia/archive/397e6877116006c8591cbe14a7c6d366d1e0751a.tar.gz
  sha256: 3e56026b72c631a1e16694ddd115c3a2e1de6a89121db316775a5375819fb930

build:
  number: 0

requirements:
  build:
    - gcc  # [not osx]
    - llvm  # [osx]
    - cmake
    - libgcc
  run:
    - libgcc

test:
  commands:
    - Sibelia --version

about:
  home: https://github.com/bioinf/Sibelia
  license: GPLv2
  summary: "Genome comparison via de Bruijn graph."

extra:
  recipe-maintainers:
    - nickp60
