package:
  name: stacks
  version: "2.0Beta2"

build:
  skip: True # [osx]
  number: 0
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

source:
  fn: stacks-2.0Beta2.tar.gz
  md5: d81959aedfa2625da3fafd5cfdf77a91
  url: http://catchenlab.life.illinois.edu/stacks/source/stacks-2.0Beta2.tar.gz

  # A patch to allow using gcc < 4.9 for compilation
  # Should be removed when a newer gcc will be available in conda
  #patches:
  #  - "gcc48.patch"

requirements:
  build:
    - gcc # [linux]
    - zlib {{CONDA_ZLIB}}*
    - sparsehash
    - boost {{CONDA_BOOST}}*
  run:
    - perl
    - velvet
    - libgcc # [linux]
    - zlib {{CONDA_ZLIB}}*
    - sparsehash
    - boost {{CONDA_BOOST}}*

test:
  commands:
    - command -v cstacks
    - command -v pstacks
    - command -v process_radtags
    - command -v clone_filter

about:
  home: http://catchenlab.life.illinois.edu/stacks/
  license: GPL
  summary: Stacks is a software pipeline for building loci from RAD-seq
